### ISSUE TITLE
digitalWriteFast does not appear to work on AVR4809

### ISSUE THREAD

**Issue by paulskirk53** [ArminJo/digitalWriteFast#1]
I included the library :

`#include <digitalWriteFast.h>`

The code snippet below toggles a Led:

```
void lightup()
{
  for (int i = 0; i < 10; i++)
  {
    digitalWrite(ledpin, HIGH);
    delay(500);
    digitalWrite(ledpin, LOW);
    delay(500);
  }
```

But the code below does not

```
void lightup()
{
  for (int i = 0; i < 10; i++)
  {
    digitalWriteFast(ledpin, HIGH);
    delay(500);
    digitalWriteFast(ledpin, LOW);
    delay(500);
  }
```
Perhaps I missed something?

**Comment by ArminJo** [comment]
Maybe different pin numbering scheme?

**Comment by paulskirk53** [comment]
Ah yes, although i've included the Arduino library, the chip architecture is different.
Thanks. :)

**Comment by Meins321** [comment]
But looks still like AVR on Arduino it is 

microchip.com/en-us/product/atmega4809

ATmega4809 is a microcontroller featuring the 8-bit AVR®  processor with hardware multiplier - running at up to 20 MHz and with up to 48 KB Flash, 6 KB SRAM and 256 bytes of EEPROM in 48-pin packages. ...

**Comment by ArminJo** [comment]
How do you think is ledpin mapped to hardware?

**Comment by paulskirk53** [comment]
looks like megacorex already has support for fast IO (digitalreadfast/ writefast) on this hardware family

 https://github.com/MCUdude/MegaCoreX

**Comment by ArminJo** [comment]
Should be fixed now 😀
