### ISSUE TITLE
Doesn't work on ATtiny3217

### ISSUE THREAD

**Issue by avandalen** [ArminJo/digitalWriteFast#2]
It doesn't work on ATtiny3217 etc..

**Comment by ArminJo** [comment]
Why

**Comment by avandalen** [comment]
This example dont work with the ATtiny3217 (but on the Arduino Nano well)

// Board = megaTinyCore > Attiny3217/3216....... w/optiboot
// Chip = ATtiny3217
// Clock = 16MHz internal

#include <digitalWriteFast.h> // https://github.com/ArminJo/digitalWriteFast
const byte outPin = 17;

void setup()
{ pinMode(outPin , OUTPUT);
  digitalWriteFast(outPin, 1); // is 0 instead of 1
  while (1) digitalToggleFast(outPin); // dont work
}

void loop()
{
}

**Comment by ArminJo** [comment]
Thanks for reporting 👍 
If you use **megaTinyCore**, you cannot use "#include digitalWriteFast.h" because megaTinyCore has it own digitalWriteFast function set, except digitalToggleFast().

**Comment by avandalen** [comment]
Thanks, I didn't know
