### ISSUE TITLE
PortManipulation is still faster than digitalWriteFast

### ISSUE THREAD

**Issue by avandalen** [ArminJo/digitalWriteFast#3]
Hi ArminJo

See here a program where PortManipulation is still faster than digitalWriteFast.
Perhaps there is further optimisation possible?

`#include <digitalWriteFast.h> // https://github.com/ArminJo/digitalWriteFast

void setup()
{ pinMode(9, OUTPUT);
  while (1)
  { //digitalWriteFast(9, 1); // 126ns 2,67MHz
    //digitalWriteFast(9, 0); // 249ns

    PORTB = B00000010; // 63ns 4MHz
    PORTB = B00000000; // 186.5ns
  }

}

void loop() // while (1) is faster than loop()
{
}`

**Comment by ArminJo** [comment]
Look at the assembler generated by avr-objdump -h -S program_name.elf  >program_name.lss
and you will see the reason 😀 .

**Comment by avandalen** [comment]
Yes I will do this, thanks for the tip...
Albert
