### ISSUE TITLE
Fast functions not single-statement safe...

### ISSUE THREAD

**Issue by WestfW** [ArminJo/digitalWriteFast#7]
the digitalWriteFast() and etc macros will not compile properly as "single statements", causing constructs like the following to fail with an "'else' without a previous 'if' error"

```
void setup() {
  if (digitalRead(1) == HIGH)
    digitalWriteFast(2, HIGH);
  else
    digitalWriteFast(3, HIGH);
}
```

This can be fixed (in a standard way) by wrapping them in a 1-time loop:
```
#define digitalWriteFast(P, V) \
 do { \
  if (__builtin_constant_p(P)) { \
    BIT_WRITE(*__digitalPinToPortReg(P), __digitalPinToBit(P), (V)); \
  } else { \
    digitalWrite((P), (V)); \
  } \
 } while (0)
```

**Comment by ArminJo** [comment]
Thanks for reporting 👍 
Are the changes, I have made, sufficient?
If so, I will issue a new release.

**Comment by WestfW** [comment]
It looks good to me...
Thanks for the quick response!
